### ISSUE TITLE
error TS2589: Type instantiation is excessively deep and possibly infinite.

### ISSUE THREAD

**Issue by lcsvcn** [vercel/modelfusion#340]
error TS2589: Type instantiation is excessively deep and possibly infinite.

<img width="936" alt="Screenshot 2024-05-13 at 12 48 35" src="https://github.com/vercel/modelfusion/assets/6011385/563b28a5-6d01-4622-af6d-782c39f18968">

After bump zod from 3.22.4 to 3.23.8 started receiving this issue.

**Comment by carloslfu** [comment]
I had the same error. I had to go to `zod` `v3.22.4`.

**Comment by 0XPW87** [comment]
Can confirm. For me, this also causes intellisense to become unusable almost anywhere in the file, and it seems to be a common thing with zod.

out of curiosity, is there any way for me to replace zod with typebox in this project? A wrapper or something, maybe?

**Comment by ispykenny** [comment]
> I had the same error. I had to go to `zod` `v3.22.4`.

Nearly one year later and this still helped. Thank you.
